image:
  file: .gitpod.Dockerfile
ports:
    - port: 5432
tasks:
             # データベース techdbを作成
  - command: psql -c "CREATE DATABASE techdb OWNER gitpod;"
             # スキーマ techscを作成
          && psql -d techdb -c "CREATE SCHEMA techsc AUTHORIZATION gitpod;" 
             # テーブル作成用SQLファイルを読み込む
          && psql -d techdb -f ./DB/table.sql
