image:
  file: .gitpod.Dockerfile
ports:
    - port: 5432
tasks:
  - command: psql -c "CREATE DATABASE tech OWNER gitpod;" \
    && psql -c "CREATE SCHEMA AUTHORIZATION tech;" \
    && psql -c "CREATE TABLE memo ( title VARCHAR(20) NOT NULL, note TEXT NOT NULL, PRIMARY KEY (title) ) WITHOUT OIDS;"
