image:
  file: .gitpod.Dockerfile
ports:
    - port: 5432
tasks:
  - command: psql -c "CREATE DATABASE techdb OWNER gitpod;" 
          && psql -d techdb -c "CREATE SCHEMA techsc AUTHORIZATION gitpod;" 
          && psql -d techdb -f /DB/table.sql
