image:
  file: .gitpod.Dockerfile
ports:
    - port: 5432
tasks:
  - command: psql -c "CREATE ROLE tech WITH LOGIN PASSWORD 'tech';"
  - command: export PGPASSWORD='tech'
  - command: psql -U "tech" -c "CREATE DATABASE tech OWNER tech;"
