image:
  file: .gitpod.Dockerfile
ports:
    - port: 5432
tasks:
  - init: psql -c "CREATE DATABASE tech OWNER gitpod;"
    command: psql -c "CREATE SCHEMA AUTHORIZATION tech;"
    command: psql -c "CREATE TABLE memo ( title VARCHAR(20) NOT NULL, note TEXT NOT NULL, PRIMARY KEY (title) ) WITHOUT OIDS;"
