image:
  file: .gitpod.Dockerfile
ports:
    - port: 5432

# データベース techdbを作成
# スキーマ techscを作成
# テーブル作成用SQLファイルを読み込む
tasks:
  - command: psql -c "CREATE DATABASE techdb OWNER gitpod;"       
          && psql -d techdb -c "CREATE SCHEMA techsc AUTHORIZATION gitpod;" 
          && psql -d techdb -f ./DB/table.sql
